export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="ys"
plugins=(git extract zsh-syntax-highlighting zsh-autosuggestions kubectl-context)
fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src
source $ZSH/oh-my-zsh.sh